# Generated by Django 4.2.2 on 2025-12-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_coupon_newsletter_productreview_productvariant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recentlyviewed',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recentlyviewed',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
