# Generated by Django 4.2.2 on 2025-12-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('complete', False)), fields=('customer',), name='unique_incomplete_order_per_customer'),
        ),
    ]
