# Generated by Django 4.2.2 on 2026-03-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20260130_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='razorpay_payment_id',
        ),
    ]
