# Generated by Django 6.0.2 on 2026-03-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
